#ifndef CONFIG_H
#define CONFIG_H

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 800
#define LEVEL_WIDTH 6000
#define LEVEL_HEIGHT 4800
#define TOTAL_WIDTH SCREEN_WIDTH + LEVEL_WIDTH
#define TOTAL_HEIGHT SCREEN_HEIGHT + LEVEL_HEIGHT

#define MAX_OBSTACLES 50
#define PLAYER_VEL 10
#define HP_REGEN_COOLDOWN 5000

#define OBSTACLE_RESPAWN_TIME 2000

#define SHOW_BOX 0

#define MAX_TEXTURES 15

#define MAX_PROJECTILES 30
#define PROJ_SPEED 20

#define MAX_ENEMIES 50
#define ENEMY_TRACKING_INTERVAL 1000
#define ENEMY_RESPAWN_INTERVAL 2000
#define ENEMY_SPEED 12
#define ENEMY_DAMAGE 200

#define MAX_ENEMIES_INCREASE_INTERVAL 5000

#define KNOCKBACK_DURATION 250

#define PATH_TO_SAVEGAME "./savegames/save.bin"
#define AUTOSAVE 0

#define PLAYER_BUFFER 61
#define OBSGROUP_BUFFER 4 + 25 * MAX_OBSTACLES
#define ENEMYGROUP_BUFFER 8 + 13 * MAX_ENEMIES

#define SCOREBOARD_FILE "./scoreboard.bin"
#define LOG_FILE "./log.txt"
#endif